### ISSUE TITLE
word verification in the last version

### ISSUE THREAD

**Issue by OfirKariv** [liorp/milan#1]
Hey, something went wrong with the last version.

This word is acceptable : 
התנפל
But this word is not:
התנפץ

**Comment by liorp** [comment]
That’s a new feature- the guess is now verified against the list of available words on the server.

**Comment by OfirKariv** [comment]
@liorp 
Thank you for your quick reply.
As a client, it is not clear which kind of words are acceptable and which doesn't. 
Honestly, I was about to stop playing it for good, but when I saw it is open-source, I thought I could ask you about it before.

**Comment by liorp** [comment]
Happy you’re enjoying your game :)  
The list of words is found under `resources/words.json`  
This way, it mimics the behavior of the original wordle.  
Of course, the list is incomplete. You are welcomed to submit a PR.  
I may add a feature to toggle settings and game modes in the future.

**Comment by OfirKariv** [comment]
Again, as I said, it was just fine yesterday, but now it lacks a lot of words

**Comment by liorp** [comment]
I have added a list of words from wiktionary.
